[tool.commitizen]
version = "0.2.0"
changelog_incremental = true
version_files = [
    "pyproject.toml:version"
]

[tool.poetry]
name = "holisticai"
version = "0.2.0"
description = "Holistic AI Library"
authors = ["Research Team"]
maintainers = ["Research Team <researchteam@holisticai.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
scikit-learn = ">=1.0.2"
seaborn = ">=0.11.2"
tqdm = "^4.64.1"
cvxpy = {extras = ["cbc"], version = "^1.3.0"}
cvxopt = "^1.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pre-commit = "^3.0.0"
commitizen = "^2.40.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
